import re 
text = "Alan Turing was a pioneer of theoritical computer science and artificial intelligence. He was born on 23 june 1912 in Maida Vale, London"
res = re.findall("\AAlan",text)
print("Result for \A = ",res)
print("-"*79)
res = re.findall(r'\bLon',text)
print("Result for \\b = ",res)
print("-"*79)
res = re.findall(r'ring\b',text)
print("Result for \\b = ",res)
print("-"*79)
res = re.findall('\d',text)
print("Result for \d = ",res)
print("-"*79)
res = re.findall('\D',text)
print("Result for \D = ",res)
print("-"*79)
res = re.findall('\s',text)
print("Result for \s = ",res)
print("-"*79)
res = re.findall('\S',text)
print("Result for \S = ",res)
print("-"*79)
res = re.findall('\w',text)
print("Result for \w = ",res)
print("-"*79)
res = re.findall('\W',text)
print("Result for \W = ",res)
print("-"*79)
res = re.findall('\Z',text)
print("Result for \Z = ",res)