string1 = '''I'm a "Geek"'''
print("Initial String with use of Triple Quotes:")
print(string1)
print("\nEscaping Single Quote:")
print('I\'m a "Geek"')
print("\nEscaping Double Quotes:")
print("I'm a \"Geek\"")
print("\nEscaping Backslashes:")
print("C:\\Python\\Geeks\\")
print("\nTab:")
print("Hi\tGeeks")
print("\nNew Line:")
print("Python\nGeeks")
print("\nRaw String:")
print(r"C:\Python\Geeks\\")